//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JediWebApplication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JediContract", Namespace="http://schemas.datacontract.org/2004/07/JediWebService")]
    [System.SerializableAttribute()]
    public partial class JediContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.ServiceReference1.CaracteristiqueContract[] CaracteristiquesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSithField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.ServiceReference1.CaracteristiqueContract[] Caracteristiques {
            get {
                return this.CaracteristiquesField;
            }
            set {
                if ((object.ReferenceEquals(this.CaracteristiquesField, value) != true)) {
                    this.CaracteristiquesField = value;
                    this.RaisePropertyChanged("Caracteristiques");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSith {
            get {
                return this.IsSithField;
            }
            set {
                if ((this.IsSithField.Equals(value) != true)) {
                    this.IsSithField = value;
                    this.RaisePropertyChanged("IsSith");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaracteristiqueContract", Namespace="http://schemas.datacontract.org/2004/07/JediWebService")]
    [System.SerializableAttribute()]
    public partial class CaracteristiqueContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.ServiceReference1.EDefCaracteristique DefinitionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.ServiceReference1.ETypeCaracteristique TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValeurField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.ServiceReference1.EDefCaracteristique Definition {
            get {
                return this.DefinitionField;
            }
            set {
                if ((this.DefinitionField.Equals(value) != true)) {
                    this.DefinitionField = value;
                    this.RaisePropertyChanged("Definition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.ServiceReference1.ETypeCaracteristique Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Valeur {
            get {
                return this.ValeurField;
            }
            set {
                if ((this.ValeurField.Equals(value) != true)) {
                    this.ValeurField = value;
                    this.RaisePropertyChanged("Valeur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EDefCaracteristique", Namespace="http://schemas.datacontract.org/2004/07/EntitiesLayer")]
    public enum EDefCaracteristique : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Force = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Defense = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sante = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Chance = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETypeCaracteristique", Namespace="http://schemas.datacontract.org/2004/07/EntitiesLayer")]
    public enum ETypeCaracteristique : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Jedi = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stade = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StadeContract", Namespace="http://schemas.datacontract.org/2004/07/JediWebService")]
    [System.SerializableAttribute()]
    public partial class StadeContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.ServiceReference1.CaracteristiqueContract[] CaracsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NbPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaneteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.ServiceReference1.CaracteristiqueContract[] Caracs {
            get {
                return this.CaracsField;
            }
            set {
                if ((object.ReferenceEquals(this.CaracsField, value) != true)) {
                    this.CaracsField = value;
                    this.RaisePropertyChanged("Caracs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbPlace {
            get {
                return this.NbPlaceField;
            }
            set {
                if ((this.NbPlaceField.Equals(value) != true)) {
                    this.NbPlaceField = value;
                    this.RaisePropertyChanged("NbPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Planete {
            get {
                return this.PlaneteField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaneteField, value) != true)) {
                    this.PlaneteField = value;
                    this.RaisePropertyChanged("Planete");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchContract", Namespace="http://schemas.datacontract.org/2004/07/JediWebService")]
    [System.SerializableAttribute()]
    public partial class MatchContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdJediVainqueurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.ServiceReference1.JediContract Jedi1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.ServiceReference1.JediContract Jedi2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.ServiceReference1.StadeContract StadeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJediVainqueur {
            get {
                return this.IdJediVainqueurField;
            }
            set {
                if ((this.IdJediVainqueurField.Equals(value) != true)) {
                    this.IdJediVainqueurField = value;
                    this.RaisePropertyChanged("IdJediVainqueur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.ServiceReference1.JediContract Jedi1 {
            get {
                return this.Jedi1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Jedi1Field, value) != true)) {
                    this.Jedi1Field = value;
                    this.RaisePropertyChanged("Jedi1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.ServiceReference1.JediContract Jedi2 {
            get {
                return this.Jedi2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Jedi2Field, value) != true)) {
                    this.Jedi2Field = value;
                    this.RaisePropertyChanged("Jedi2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.ServiceReference1.StadeContract Stade {
            get {
                return this.StadeField;
            }
            set {
                if ((object.ReferenceEquals(this.StadeField, value) != true)) {
                    this.StadeField = value;
                    this.RaisePropertyChanged("Stade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TournoiContract", Namespace="http://schemas.datacontract.org/2004/07/JediWebService")]
    [System.SerializableAttribute()]
    public partial class TournoiContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.ServiceReference1.MatchContract[] MatchsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.ServiceReference1.MatchContract[] Matchs {
            get {
                return this.MatchsField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchsField, value) != true)) {
                    this.MatchsField = value;
                    this.RaisePropertyChanged("Matchs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJedis", ReplyAction="http://tempuri.org/IService1/GetJedisResponse")]
        JediWebApplication.ServiceReference1.JediContract[] GetJedis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJedis", ReplyAction="http://tempuri.org/IService1/GetJedisResponse")]
        System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.JediContract[]> GetJedisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesByJedi", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesByJediResponse")]
        JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesByJedi(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesByJedi", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesByJediResponse")]
        System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesByJediAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddJedi", ReplyAction="http://tempuri.org/IService1/AddJediResponse")]
        void AddJedi(string nom, bool isSith, JediWebApplication.ServiceReference1.CaracteristiqueContract force, JediWebApplication.ServiceReference1.CaracteristiqueContract defense, JediWebApplication.ServiceReference1.CaracteristiqueContract chance, JediWebApplication.ServiceReference1.CaracteristiqueContract sante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddJedi", ReplyAction="http://tempuri.org/IService1/AddJediResponse")]
        System.Threading.Tasks.Task AddJediAsync(string nom, bool isSith, JediWebApplication.ServiceReference1.CaracteristiqueContract force, JediWebApplication.ServiceReference1.CaracteristiqueContract defense, JediWebApplication.ServiceReference1.CaracteristiqueContract chance, JediWebApplication.ServiceReference1.CaracteristiqueContract sante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modJedi", ReplyAction="http://tempuri.org/IService1/modJediResponse")]
        void modJedi(int id, string nom, bool isSith, JediWebApplication.ServiceReference1.CaracteristiqueContract force, JediWebApplication.ServiceReference1.CaracteristiqueContract defense, JediWebApplication.ServiceReference1.CaracteristiqueContract chance, JediWebApplication.ServiceReference1.CaracteristiqueContract sante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modJedi", ReplyAction="http://tempuri.org/IService1/modJediResponse")]
        System.Threading.Tasks.Task modJediAsync(int id, string nom, bool isSith, JediWebApplication.ServiceReference1.CaracteristiqueContract force, JediWebApplication.ServiceReference1.CaracteristiqueContract defense, JediWebApplication.ServiceReference1.CaracteristiqueContract chance, JediWebApplication.ServiceReference1.CaracteristiqueContract sante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delJedi", ReplyAction="http://tempuri.org/IService1/delJediResponse")]
        void delJedi(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delJedi", ReplyAction="http://tempuri.org/IService1/delJediResponse")]
        System.Threading.Tasks.Task delJediAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStades", ReplyAction="http://tempuri.org/IService1/GetStadesResponse")]
        JediWebApplication.ServiceReference1.StadeContract[] GetStades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStades", ReplyAction="http://tempuri.org/IService1/GetStadesResponse")]
        System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.StadeContract[]> GetStadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesByStade", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesByStadeResponse")]
        JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesByStade(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesByStade", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesByStadeResponse")]
        System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesByStadeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStade", ReplyAction="http://tempuri.org/IService1/AddStadeResponse")]
        void AddStade(int nbPlaces, string nom, string planete, JediWebApplication.ServiceReference1.CaracteristiqueContract force, JediWebApplication.ServiceReference1.CaracteristiqueContract defense, JediWebApplication.ServiceReference1.CaracteristiqueContract chance, JediWebApplication.ServiceReference1.CaracteristiqueContract sante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStade", ReplyAction="http://tempuri.org/IService1/AddStadeResponse")]
        System.Threading.Tasks.Task AddStadeAsync(int nbPlaces, string nom, string planete, JediWebApplication.ServiceReference1.CaracteristiqueContract force, JediWebApplication.ServiceReference1.CaracteristiqueContract defense, JediWebApplication.ServiceReference1.CaracteristiqueContract chance, JediWebApplication.ServiceReference1.CaracteristiqueContract sante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modStade", ReplyAction="http://tempuri.org/IService1/modStadeResponse")]
        void modStade(int id, int nbPlaces, string nom, string planete, JediWebApplication.ServiceReference1.CaracteristiqueContract force, JediWebApplication.ServiceReference1.CaracteristiqueContract defense, JediWebApplication.ServiceReference1.CaracteristiqueContract chance, JediWebApplication.ServiceReference1.CaracteristiqueContract sante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modStade", ReplyAction="http://tempuri.org/IService1/modStadeResponse")]
        System.Threading.Tasks.Task modStadeAsync(int id, int nbPlaces, string nom, string planete, JediWebApplication.ServiceReference1.CaracteristiqueContract force, JediWebApplication.ServiceReference1.CaracteristiqueContract defense, JediWebApplication.ServiceReference1.CaracteristiqueContract chance, JediWebApplication.ServiceReference1.CaracteristiqueContract sante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delStade", ReplyAction="http://tempuri.org/IService1/delStadeResponse")]
        void delStade(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delStade", ReplyAction="http://tempuri.org/IService1/delStadeResponse")]
        System.Threading.Tasks.Task delStadeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMatchs", ReplyAction="http://tempuri.org/IService1/GetMatchsResponse")]
        JediWebApplication.ServiceReference1.MatchContract[] GetMatchs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMatchs", ReplyAction="http://tempuri.org/IService1/GetMatchsResponse")]
        System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.MatchContract[]> GetMatchsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMatch", ReplyAction="http://tempuri.org/IService1/AddMatchResponse")]
        void AddMatch(int idJediVainqueur, string jedic1, string jedic2, string stadec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMatch", ReplyAction="http://tempuri.org/IService1/AddMatchResponse")]
        System.Threading.Tasks.Task AddMatchAsync(int idJediVainqueur, string jedic1, string jedic2, string stadec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modMatch", ReplyAction="http://tempuri.org/IService1/modMatchResponse")]
        void modMatch(int id, int idJediVainqueur, string jedic1, string jedic2, string stadec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modMatch", ReplyAction="http://tempuri.org/IService1/modMatchResponse")]
        System.Threading.Tasks.Task modMatchAsync(int id, int idJediVainqueur, string jedic1, string jedic2, string stadec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delMatch", ReplyAction="http://tempuri.org/IService1/delMatchResponse")]
        void delMatch(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delMatch", ReplyAction="http://tempuri.org/IService1/delMatchResponse")]
        System.Threading.Tasks.Task delMatchAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTournois", ReplyAction="http://tempuri.org/IService1/GetTournoisResponse")]
        JediWebApplication.ServiceReference1.TournoiContract[] GetTournois();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTournois", ReplyAction="http://tempuri.org/IService1/GetTournoisResponse")]
        System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.TournoiContract[]> GetTournoisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTournoi", ReplyAction="http://tempuri.org/IService1/AddTournoiResponse")]
        void AddTournoi(string nom, JediWebApplication.ServiceReference1.MatchContract match1, JediWebApplication.ServiceReference1.MatchContract match2, JediWebApplication.ServiceReference1.MatchContract match3, JediWebApplication.ServiceReference1.MatchContract match4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTournoi", ReplyAction="http://tempuri.org/IService1/AddTournoiResponse")]
        System.Threading.Tasks.Task AddTournoiAsync(string nom, JediWebApplication.ServiceReference1.MatchContract match1, JediWebApplication.ServiceReference1.MatchContract match2, JediWebApplication.ServiceReference1.MatchContract match3, JediWebApplication.ServiceReference1.MatchContract match4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModTournoi", ReplyAction="http://tempuri.org/IService1/ModTournoiResponse")]
        void ModTournoi(int id, string nom, JediWebApplication.ServiceReference1.MatchContract match1, JediWebApplication.ServiceReference1.MatchContract match2, JediWebApplication.ServiceReference1.MatchContract match3, JediWebApplication.ServiceReference1.MatchContract match4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModTournoi", ReplyAction="http://tempuri.org/IService1/ModTournoiResponse")]
        System.Threading.Tasks.Task ModTournoiAsync(int id, string nom, JediWebApplication.ServiceReference1.MatchContract match1, JediWebApplication.ServiceReference1.MatchContract match2, JediWebApplication.ServiceReference1.MatchContract match3, JediWebApplication.ServiceReference1.MatchContract match4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delTournoi", ReplyAction="http://tempuri.org/IService1/delTournoiResponse")]
        void delTournoi(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delTournoi", ReplyAction="http://tempuri.org/IService1/delTournoiResponse")]
        System.Threading.Tasks.Task delTournoiAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiques", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesResponse")]
        JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiques();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiques", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesResponse")]
        System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesJediForce", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesJediForceResponse")]
        JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesJediForce();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesJediForce", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesJediForceResponse")]
        System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesJediForceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesJediDefense", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesJediDefenseResponse")]
        JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesJediDefense();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesJediDefense", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesJediDefenseResponse")]
        System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesJediDefenseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesJediChance", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesJediChanceResponse")]
        JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesJediChance();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesJediChance", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesJediChanceResponse")]
        System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesJediChanceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesJediSante", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesJediSanteResponse")]
        JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesJediSante();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesJediSante", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesJediSanteResponse")]
        System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesJediSanteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesStadeForce", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesStadeForceResponse")]
        JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesStadeForce();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesStadeForce", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesStadeForceResponse")]
        System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesStadeForceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesStadeDefense", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesStadeDefenseResponse")]
        JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesStadeDefense();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesStadeDefense", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesStadeDefenseResponse")]
        System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesStadeDefenseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesStadeChance", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesStadeChanceResponse")]
        JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesStadeChance();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesStadeChance", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesStadeChanceResponse")]
        System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesStadeChanceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesStadeSante", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesStadeSanteResponse")]
        JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesStadeSante();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaracteristiquesStadeSante", ReplyAction="http://tempuri.org/IService1/GetCaracteristiquesStadeSanteResponse")]
        System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesStadeSanteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCarac", ReplyAction="http://tempuri.org/IService1/AddCaracResponse")]
        void AddCarac(string nom, int valeur, JediWebApplication.ServiceReference1.EDefCaracteristique definition, JediWebApplication.ServiceReference1.ETypeCaracteristique type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCarac", ReplyAction="http://tempuri.org/IService1/AddCaracResponse")]
        System.Threading.Tasks.Task AddCaracAsync(string nom, int valeur, JediWebApplication.ServiceReference1.EDefCaracteristique definition, JediWebApplication.ServiceReference1.ETypeCaracteristique type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modCarac", ReplyAction="http://tempuri.org/IService1/modCaracResponse")]
        void modCarac(int id, string nom, int valeur, JediWebApplication.ServiceReference1.EDefCaracteristique definition, JediWebApplication.ServiceReference1.ETypeCaracteristique type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modCarac", ReplyAction="http://tempuri.org/IService1/modCaracResponse")]
        System.Threading.Tasks.Task modCaracAsync(int id, string nom, int valeur, JediWebApplication.ServiceReference1.EDefCaracteristique definition, JediWebApplication.ServiceReference1.ETypeCaracteristique type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delCarac", ReplyAction="http://tempuri.org/IService1/delCaracResponse")]
        void delCarac(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delCarac", ReplyAction="http://tempuri.org/IService1/delCaracResponse")]
        System.Threading.Tasks.Task delCaracAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : JediWebApplication.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<JediWebApplication.ServiceReference1.IService1>, JediWebApplication.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JediWebApplication.ServiceReference1.JediContract[] GetJedis() {
            return base.Channel.GetJedis();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.JediContract[]> GetJedisAsync() {
            return base.Channel.GetJedisAsync();
        }
        
        public JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesByJedi(int id) {
            return base.Channel.GetCaracteristiquesByJedi(id);
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesByJediAsync(int id) {
            return base.Channel.GetCaracteristiquesByJediAsync(id);
        }
        
        public void AddJedi(string nom, bool isSith, JediWebApplication.ServiceReference1.CaracteristiqueContract force, JediWebApplication.ServiceReference1.CaracteristiqueContract defense, JediWebApplication.ServiceReference1.CaracteristiqueContract chance, JediWebApplication.ServiceReference1.CaracteristiqueContract sante) {
            base.Channel.AddJedi(nom, isSith, force, defense, chance, sante);
        }
        
        public System.Threading.Tasks.Task AddJediAsync(string nom, bool isSith, JediWebApplication.ServiceReference1.CaracteristiqueContract force, JediWebApplication.ServiceReference1.CaracteristiqueContract defense, JediWebApplication.ServiceReference1.CaracteristiqueContract chance, JediWebApplication.ServiceReference1.CaracteristiqueContract sante) {
            return base.Channel.AddJediAsync(nom, isSith, force, defense, chance, sante);
        }
        
        public void modJedi(int id, string nom, bool isSith, JediWebApplication.ServiceReference1.CaracteristiqueContract force, JediWebApplication.ServiceReference1.CaracteristiqueContract defense, JediWebApplication.ServiceReference1.CaracteristiqueContract chance, JediWebApplication.ServiceReference1.CaracteristiqueContract sante) {
            base.Channel.modJedi(id, nom, isSith, force, defense, chance, sante);
        }
        
        public System.Threading.Tasks.Task modJediAsync(int id, string nom, bool isSith, JediWebApplication.ServiceReference1.CaracteristiqueContract force, JediWebApplication.ServiceReference1.CaracteristiqueContract defense, JediWebApplication.ServiceReference1.CaracteristiqueContract chance, JediWebApplication.ServiceReference1.CaracteristiqueContract sante) {
            return base.Channel.modJediAsync(id, nom, isSith, force, defense, chance, sante);
        }
        
        public void delJedi(int id) {
            base.Channel.delJedi(id);
        }
        
        public System.Threading.Tasks.Task delJediAsync(int id) {
            return base.Channel.delJediAsync(id);
        }
        
        public JediWebApplication.ServiceReference1.StadeContract[] GetStades() {
            return base.Channel.GetStades();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.StadeContract[]> GetStadesAsync() {
            return base.Channel.GetStadesAsync();
        }
        
        public JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesByStade(int id) {
            return base.Channel.GetCaracteristiquesByStade(id);
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesByStadeAsync(int id) {
            return base.Channel.GetCaracteristiquesByStadeAsync(id);
        }
        
        public void AddStade(int nbPlaces, string nom, string planete, JediWebApplication.ServiceReference1.CaracteristiqueContract force, JediWebApplication.ServiceReference1.CaracteristiqueContract defense, JediWebApplication.ServiceReference1.CaracteristiqueContract chance, JediWebApplication.ServiceReference1.CaracteristiqueContract sante) {
            base.Channel.AddStade(nbPlaces, nom, planete, force, defense, chance, sante);
        }
        
        public System.Threading.Tasks.Task AddStadeAsync(int nbPlaces, string nom, string planete, JediWebApplication.ServiceReference1.CaracteristiqueContract force, JediWebApplication.ServiceReference1.CaracteristiqueContract defense, JediWebApplication.ServiceReference1.CaracteristiqueContract chance, JediWebApplication.ServiceReference1.CaracteristiqueContract sante) {
            return base.Channel.AddStadeAsync(nbPlaces, nom, planete, force, defense, chance, sante);
        }
        
        public void modStade(int id, int nbPlaces, string nom, string planete, JediWebApplication.ServiceReference1.CaracteristiqueContract force, JediWebApplication.ServiceReference1.CaracteristiqueContract defense, JediWebApplication.ServiceReference1.CaracteristiqueContract chance, JediWebApplication.ServiceReference1.CaracteristiqueContract sante) {
            base.Channel.modStade(id, nbPlaces, nom, planete, force, defense, chance, sante);
        }
        
        public System.Threading.Tasks.Task modStadeAsync(int id, int nbPlaces, string nom, string planete, JediWebApplication.ServiceReference1.CaracteristiqueContract force, JediWebApplication.ServiceReference1.CaracteristiqueContract defense, JediWebApplication.ServiceReference1.CaracteristiqueContract chance, JediWebApplication.ServiceReference1.CaracteristiqueContract sante) {
            return base.Channel.modStadeAsync(id, nbPlaces, nom, planete, force, defense, chance, sante);
        }
        
        public void delStade(int id) {
            base.Channel.delStade(id);
        }
        
        public System.Threading.Tasks.Task delStadeAsync(int id) {
            return base.Channel.delStadeAsync(id);
        }
        
        public JediWebApplication.ServiceReference1.MatchContract[] GetMatchs() {
            return base.Channel.GetMatchs();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.MatchContract[]> GetMatchsAsync() {
            return base.Channel.GetMatchsAsync();
        }
        
        public void AddMatch(int idJediVainqueur, string jedic1, string jedic2, string stadec) {
            base.Channel.AddMatch(idJediVainqueur, jedic1, jedic2, stadec);
        }
        
        public System.Threading.Tasks.Task AddMatchAsync(int idJediVainqueur, string jedic1, string jedic2, string stadec) {
            return base.Channel.AddMatchAsync(idJediVainqueur, jedic1, jedic2, stadec);
        }
        
        public void modMatch(int id, int idJediVainqueur, string jedic1, string jedic2, string stadec) {
            base.Channel.modMatch(id, idJediVainqueur, jedic1, jedic2, stadec);
        }
        
        public System.Threading.Tasks.Task modMatchAsync(int id, int idJediVainqueur, string jedic1, string jedic2, string stadec) {
            return base.Channel.modMatchAsync(id, idJediVainqueur, jedic1, jedic2, stadec);
        }
        
        public void delMatch(int id) {
            base.Channel.delMatch(id);
        }
        
        public System.Threading.Tasks.Task delMatchAsync(int id) {
            return base.Channel.delMatchAsync(id);
        }
        
        public JediWebApplication.ServiceReference1.TournoiContract[] GetTournois() {
            return base.Channel.GetTournois();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.TournoiContract[]> GetTournoisAsync() {
            return base.Channel.GetTournoisAsync();
        }
        
        public void AddTournoi(string nom, JediWebApplication.ServiceReference1.MatchContract match1, JediWebApplication.ServiceReference1.MatchContract match2, JediWebApplication.ServiceReference1.MatchContract match3, JediWebApplication.ServiceReference1.MatchContract match4) {
            base.Channel.AddTournoi(nom, match1, match2, match3, match4);
        }
        
        public System.Threading.Tasks.Task AddTournoiAsync(string nom, JediWebApplication.ServiceReference1.MatchContract match1, JediWebApplication.ServiceReference1.MatchContract match2, JediWebApplication.ServiceReference1.MatchContract match3, JediWebApplication.ServiceReference1.MatchContract match4) {
            return base.Channel.AddTournoiAsync(nom, match1, match2, match3, match4);
        }
        
        public void ModTournoi(int id, string nom, JediWebApplication.ServiceReference1.MatchContract match1, JediWebApplication.ServiceReference1.MatchContract match2, JediWebApplication.ServiceReference1.MatchContract match3, JediWebApplication.ServiceReference1.MatchContract match4) {
            base.Channel.ModTournoi(id, nom, match1, match2, match3, match4);
        }
        
        public System.Threading.Tasks.Task ModTournoiAsync(int id, string nom, JediWebApplication.ServiceReference1.MatchContract match1, JediWebApplication.ServiceReference1.MatchContract match2, JediWebApplication.ServiceReference1.MatchContract match3, JediWebApplication.ServiceReference1.MatchContract match4) {
            return base.Channel.ModTournoiAsync(id, nom, match1, match2, match3, match4);
        }
        
        public void delTournoi(int id) {
            base.Channel.delTournoi(id);
        }
        
        public System.Threading.Tasks.Task delTournoiAsync(int id) {
            return base.Channel.delTournoiAsync(id);
        }
        
        public JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiques() {
            return base.Channel.GetCaracteristiques();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesAsync() {
            return base.Channel.GetCaracteristiquesAsync();
        }
        
        public JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesJediForce() {
            return base.Channel.GetCaracteristiquesJediForce();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesJediForceAsync() {
            return base.Channel.GetCaracteristiquesJediForceAsync();
        }
        
        public JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesJediDefense() {
            return base.Channel.GetCaracteristiquesJediDefense();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesJediDefenseAsync() {
            return base.Channel.GetCaracteristiquesJediDefenseAsync();
        }
        
        public JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesJediChance() {
            return base.Channel.GetCaracteristiquesJediChance();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesJediChanceAsync() {
            return base.Channel.GetCaracteristiquesJediChanceAsync();
        }
        
        public JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesJediSante() {
            return base.Channel.GetCaracteristiquesJediSante();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesJediSanteAsync() {
            return base.Channel.GetCaracteristiquesJediSanteAsync();
        }
        
        public JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesStadeForce() {
            return base.Channel.GetCaracteristiquesStadeForce();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesStadeForceAsync() {
            return base.Channel.GetCaracteristiquesStadeForceAsync();
        }
        
        public JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesStadeDefense() {
            return base.Channel.GetCaracteristiquesStadeDefense();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesStadeDefenseAsync() {
            return base.Channel.GetCaracteristiquesStadeDefenseAsync();
        }
        
        public JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesStadeChance() {
            return base.Channel.GetCaracteristiquesStadeChance();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesStadeChanceAsync() {
            return base.Channel.GetCaracteristiquesStadeChanceAsync();
        }
        
        public JediWebApplication.ServiceReference1.CaracteristiqueContract[] GetCaracteristiquesStadeSante() {
            return base.Channel.GetCaracteristiquesStadeSante();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.ServiceReference1.CaracteristiqueContract[]> GetCaracteristiquesStadeSanteAsync() {
            return base.Channel.GetCaracteristiquesStadeSanteAsync();
        }
        
        public void AddCarac(string nom, int valeur, JediWebApplication.ServiceReference1.EDefCaracteristique definition, JediWebApplication.ServiceReference1.ETypeCaracteristique type) {
            base.Channel.AddCarac(nom, valeur, definition, type);
        }
        
        public System.Threading.Tasks.Task AddCaracAsync(string nom, int valeur, JediWebApplication.ServiceReference1.EDefCaracteristique definition, JediWebApplication.ServiceReference1.ETypeCaracteristique type) {
            return base.Channel.AddCaracAsync(nom, valeur, definition, type);
        }
        
        public void modCarac(int id, string nom, int valeur, JediWebApplication.ServiceReference1.EDefCaracteristique definition, JediWebApplication.ServiceReference1.ETypeCaracteristique type) {
            base.Channel.modCarac(id, nom, valeur, definition, type);
        }
        
        public System.Threading.Tasks.Task modCaracAsync(int id, string nom, int valeur, JediWebApplication.ServiceReference1.EDefCaracteristique definition, JediWebApplication.ServiceReference1.ETypeCaracteristique type) {
            return base.Channel.modCaracAsync(id, nom, valeur, definition, type);
        }
        
        public void delCarac(int id) {
            base.Channel.delCarac(id);
        }
        
        public System.Threading.Tasks.Task delCaracAsync(int id) {
            return base.Channel.delCaracAsync(id);
        }
    }
}
